cmake_minimum_required(VERSION 3.19)
project(inctest LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
if (MSVC)
  add_compile_options(/utf-8 /W4)
endif()
find_package(Qt6 REQUIRED COMPONENTS Widgets)
foreach(t A B C D)
  add_library(${t} STATIC ${t}.cpp)
  target_link_libraries(${t} PRIVATE Qt6::Widgets)
endforeach()
